- name: Install chocolatey packages
  win_chocolatey:
    name:
    - googlechrome
    - firefox
    - procexp
    - putty
    - git
    - vscode
    - sourcetree
    - cmdermini
    - nodejs-lts
    - nvm
    - yarn
    state: present

- name: Create a shortcut for Cmder on the desktop
  win_shortcut:
    src: C:\tools\cmdermini\Cmder.exe
    dest: Desktop\Cmder.lnk
